var quanjiniao_run = {
    path:"images/monster2.png",
    images:[
        {
            x:154,
            y:375,
            width:87,
            height:68
        },
        {
            x:1,
            y:215,
            width:70,
            height:68
        },
        {
            x:1,
            y:423,
            width:73,
            height:68
        },
        {
            x:1,
            y:148,
            width:71,
            height:66
        },
        {
            x:1,
            y:353,
            width:71,
            height:69
        },
        {
            x:1,
            y:284,
            width:70,
            height:68
        }
    ]
}
var quanjiniao_attack = {
    path:"images/monster2.png",
    images:[
        {
            x:75,
            y:252,
            width:77,
            height:67
        },
        {
            x:75,
            y:388,
            width:78,
            height:84
        },
        {
            x:154,
            y:290,
            width:86,
            height:84
        },
        {
            x:154,
            y:69,
            width:83,
            height:84
        },
        {
            x:154,
            y:1,
            width:78,
            height:67
        },
        {
            x:75,
            y:320,
            width:77,
            height:67
        },
        {
            x:246,
            y:213,
            width:97,
            height:83
        },
        {
            x:354,
            y:141,
            width:100,
            height:84
        },
        {
            x:246,
            y:297,
            width:98,
            height:84
        },
        {
            x:154,
            y:444,
            width:91,
            height:67
        }
    ]
};
